name: Check code

on:
  workflow_call:

jobs:
  check-code:
    runs-on: ubuntu-latest  # Type de runner
    steps:
      - name: Checkout du projet
        uses: actions/checkout@v6

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
            pixi-version: v0.63.0

      - name: Lancer les tests avec Pixi
        run: pixi run --environment check ruff check
