name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:

jobs:
  infos:
    uses: ./.github/workflows/_reusable/infos.yml

  checks:
    needs: infos
    uses: ./.github/workflows/_reusable/checks.yml
  tests:
    needs: checks
    #if: github.event_name == 'pull_request'
    uses: ./.github/workflows/_reusable/tests.yml