name: CI

on:
  push:


jobs:
  infos:
    uses: ./.github/workflows/_reusable/infos.yml

  checks:
    needs: infos
    uses: ./.github/workflows/_reusable/checks.yml
  tests:
    needs: checks
    uses: ./.github/workflows/_reusable/tests.yml