name: CI

on:
  push:


jobs:
  infos:
    uses: ./.github/workflows/_infos.yml

  checks:
    needs: infos
    uses: ./.github/workflows/_checks.yml
  tests:
    needs: checks
    uses: ./.github/workflows/_tests.yml